### ISSUE TITLE
Error message during install

### ISSUE THREAD

**Issue by andrewwong2000** [michaelmerg/verse-calendar-sync#2]
Hi Michael,

Was looking to try out your extension, but it seems the GoogleAPI is rejecting your oauth id ? 

Auth error: OAuth2 request failed: Service responded with error: 'bad client id: 789975739772-pecbpn39f877ks1f3ciqk3psg7t8o02h.apps.googleusercontent.com'

Appreciate if you can advise what needs to be done to get around this ?

Thanks,
Andrew

**Comment by michaelmerg** [comment]
Hi Andrew,
the extension in not publicly shared on the Chrome Web Store. Here is a link to the extension: https://chrome.google.com/webstore/detail/verse-to-google-calendar/bnhjkllfdfjdpempcgbkpabjncoijehd

If you want to add new features I think you need to create your own project + client id in the Google Developer Console in order to run it in development mode.

Cheers,
Michael
